APPLY_FIXES: all
DISABLE:
  - COPYPASTE
DISABLE_LINTERS:
  - CSS_STYLELINT
  - GO_GOLANGCI_LINT
  - REPOSITORY_KICS
  - SPELL_LYCHEE
  - REPOSITORY_TRIVY
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

# Spelling
SPELL_CSPELL_ANALYZE_FILE_NAMES: false

# yaml v8r
YAML_V8R_DISABLE_ERRORS: true
